INSERT INTO CATEGORY
(ID, CATEGORY_DESCRIPTION, CATEGORY_NAME)
VALUES
(1, 'Food', 'Food');

INSERT INTO CATEGORY
(ID, CATEGORY_DESCRIPTION, CATEGORY_NAME)
VALUES
(2, 'Oranges', 'Oranges');

INSERT INTO CATEGORY
(ID, CATEGORY_DESCRIPTION, CATEGORY_NAME)
VALUES
(3, 'Electronics', 'Electronics');

INSERT INTO CATEGORY
(ID, CATEGORY_DESCRIPTION, CATEGORY_NAME)
VALUES
(4, 'Televison', 'Televison');