INSERT INTO PRODUCT
(CAN_DISPLAY, IS_AUTOMOTIVE, IS_DELETED, IS_INTERNATIONAL, LONG_DESCRIPTION, PCODE, NAME, SHORT_DESCRIPTION, CATEGORY_ID, PARENT_CATEGORY_ID)
VALUES
(1, 0, 0, 1, '70 inch Samsung Television with Retina Display', 'P2345872', 'Samsung 70 inch TV', '', 4, 3);

INSERT INTO PRODUCT
(CAN_DISPLAY, IS_AUTOMOTIVE, IS_DELETED, IS_INTERNATIONAL, LONG_DESCRIPTION, PCODE, NAME, SHORT_DESCRIPTION, CATEGORY_ID, PARENT_CATEGORY_ID)
VALUES
(1, 0, 0, 1, '60 inch Samsung Television with Retina Display', 'P2345873', 'Samsung 60 inch TV', '', 4, 3);