use ecommerce;

CREATE TABLE `CATEGORY` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CATEGORY_DESCRIPTION` VARCHAR(255) NOT NULL,
  `CATEGORY_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=LATIN1;