use ecommerce;

CREATE TABLE `PRODUCT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CAN_DISPLAY` BIT(1) NOT NULL,
  `IS_AUTOMOTIVE` BIT(1) NOT NULL,
  `IS_DELETED` BIT(1) NOT NULL,
  `IS_INTERNATIONAL` BIT(1) NOT NULL,
  `LONG_DESCRIPTION` VARCHAR(255) NOT NULL,
  `PCODE` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SHORT_DESCRIPTION` VARCHAR(255) NOT NULL,
  `CATEGORY_ID` BIGINT(20) DEFAULT NULL,
  `PARENT_CATEGORY_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CATEGORY` (`CATEGORY_ID`),
  KEY `FK_PARENT_CATEGORY` (`PARENT_CATEGORY_ID`),
  CONSTRAINT `FK_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`),
  CONSTRAINT `FK_PARENT_CATEGORY` FOREIGN KEY (`PARENT_CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=LATIN1;