use ecommerce;

CREATE TABLE `ACCOUNT` (
  `ACCOUNT_NUMBER` varchar(255) NOT NULL,
  `ACCOUNT_NAME` varchar(255) NOT NULL,
  `USER_PROFILE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
