use ecommerce;

CREATE TABLE `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(100) NOT NULL,
  `FIRST_NAME` varchar(100) NOT NULL,
  `LAST_NAME` varchar(100) NOT NULL,
  `GENDER` varchar(1) NOT NULL,
  `MEMBER_TYPE` varchar(100) NOT NULL,
  `REGISTRATION_DATE` date NOT NULL,
  `ADDRESS_ID` bigint(20) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_lmuw5yn9r834i8u1ry9jvjft4` (`REGISTRATION_DATE`),
  KEY `FKUSERADDRESS_idx` (`ADDRESS_ID`),
  KEY `FKUSERACCOUNT_idx` (`ACCOUNT_NUMBER`),
  CONSTRAINT `FK_USER_ACCOUT` FOREIGN KEY (`ACCOUNT_NUMBER`) REFERENCES `ACCOUNT` (`ACCOUNT_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
