use ecommerce;

CREATE TABLE `ACCOUNT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NUMBER` VARCHAR(255) NOT NULL,
  `ACCOUNT_NAME` VARCHAR(255) NOT NULL,
  `USER_PROFILE_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK8QIJTHY7FDACRXEPWXS7M4M6Q` (`USER_PROFILE_ID`),
  CONSTRAINT `FKGNXJXBWINQ6XLA6QO0WI5O833` FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `USER` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
