use ecommerce;

CREATE TABLE `ADDRESS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CITY` VARCHAR(255) NOT NULL,
  `HOUSE_NUMBER` VARCHAR(255) NOT NULL,
  `STATE` VARCHAR(255) NOT NULL,
  `STREET_ADDRESS` VARCHAR(255) NOT NULL,
  `ZIP_CODE` VARCHAR(255) NOT NULL,
  `ACCOUNT_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKASCOGPQ8X3GFX04OY2FR6L3I5` (`ACCOUNT_ID`),
  CONSTRAINT `FKJFTWQEBN4C1RKNBHU0QJG5W21` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;