use ecommerce;

CREATE TABLE `ADDRESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CITY` varchar(255) NOT NULL,
  `HOUSE_NUMBER` varchar(255) NOT NULL,
  `STATE` varchar(255) NOT NULL,
  `STREET_ADDRESS` varchar(255) NOT NULL,
  `ZIP_CODE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
