eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegisty: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
