version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce

#  rabbitmq:
#    container_name: rabbitmq
#    image: 'rabbitmq:management'
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  remote-config-service:
    container_name: remote-config-service
    build: ./remote-config-service
    ports:
      - "9000:9000"
#    depends_on:
#      - rabbitmq

  eureka-service-discovery:
    container_name: eureka-service-discovery
    build: ./eureka-service-discovery
    ports:
      - "8761:8761"
    depends_on:
      - remote-config-service

  category-api:
    container_name: category-api
    build: ./category-api
    ports:
      - "18100:18100"
      - "8092:8092"
    depends_on:
      - remote-config-service
      - mysqldb
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z remote-config-service 9000); do sleep 5; echo 'Waiting for remote-config-service services to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=dev /app.jar
      "

  product-api:
    container_name: product-api
    build: ./product-api
    ports:
      - "18000:18000"
      - "8091:8091"
    depends_on:
      - remote-config-service
      - mysqldb
    entrypoint: /bin/sh
    command: >
      -c "
       while ! (nc -z remote-config-service 9000); do sleep 5; echo 'Waiting and remote-config-service services to start-up...'; done;
       java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=dev /app.jar
       "
