version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
    restart: always

#  rabbitmq:
#    container_name: rabbitmq
#    image: 'rabbitmq:management'
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  remote-config-service:
    container_name: remote-config-service
    build: ./remote-config-service
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - mysqldb
#      - rabbitmq

  eureka-service-discovery:
    container_name: eureka-service-discovery
    build: ./eureka-service-discovery
    ports:
      - "8761:8761"
    depends_on:
      - remote-config-service
    command: mvn clean spring-boot:run

  product-api:
    container_name: product-api
    build: ./product-api
    ports:
      - "18000:18000"
      - "8091:8091"
    depends_on:
      - eureka-service-discovery
      - remote-config-service
      - mysqldb
    command: mvn clean spring-boot:run

  category-api:
    container_name: category-api
    build: ./category-api
    ports:
      - "18100:18100"
      - "8092:8092"
    depends_on:
      - product-api
      - eureka-service-discovery
      - remote-config-service
      - mysqldb
    command: mvn clean spring-boot:run