INSERT INTO ADDRESS
(CITY, HOUSE_NUMBER, STATE, STREET_ADDRESS, ZIP_CODE)
VALUES
('Dublin', '123', 'DUBLIN', 'Main Street', 'D01 A1B2');

INSERT INTO ADDRESS
(CITY, HOUSE_NUMBER, STATE, STREET_ADDRESS, ZIP_CODE)
VALUES
('London', '456', 'LONDON', 'Secundary Street', 'E1 A1B2');