# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-browsers-legacy

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: product-api
          command: mvn install
          working_directory: product-api
      - store_artifacts:
          path: product-api/target


      - run:
          name: category-api
          command: mvn install
          working_directory: category-api

      # generating code coverage
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)