server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abalzan/ecommerce-microservice-config
          searchPaths: product-api, category-api, address-api, user-api, database-setup, gateway-service

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/