server:
  port: 8888

#zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
#  routes:
#    spring-security-oauth-resource:
#      path: /spring-security-oauth-resource/**
#      url: http://localhost:8082/spring-security-oauth-resource
#    oauth:
#      path: /oauth/**
#      url: http://localhost:8081/spring-security-oauth-server/oauth
#
#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: 123


logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    com.andrei: DEBUG
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"